### ISSUE TITLE
 FutureWarning: 'H' is deprecated

### ISSUE THREAD

**Issue by AdamRJensen** [martavp/pv-textbook#13]
https://martavp.github.io/pv-textbook/Problems/Chapter_02/Problem2.15.html

> /tmp/ipykernel_1964/4240782977.py:17: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
>  times = pd.date_range(start=date, freq='1H', periods=24, tz=tz)

The frequency for hour is no longer "H" but "h", this should be fixed to be compatible with future versions of pandas. This probably occurs other places as well.

**Comment by rubennj** [comment]
Yes, in some notebooks Pandas warns about it, fixed.
Thanks @AdamRJensen.
